import { OperationalAlert } from '@/types/dashboard';

export const MOCK_ALERTS: OperationalAlert[] = [
  {
    id: 'alt-001',
    title: 'Low Attendance Flag: Mech Batch 2024 (Group B1)',
    description: 'Average attendance dropped to 74.2% in Thermodynamics Lab over the last two weeks.',
    severity: 'HIGH',
    category: 'Attendance Violation',
    timestamp: '2 hours ago',
    affectedEntity: 'Mechanical Dept / Batch 2024-2028',
    actionRequired: true,
  },
  {
    id: 'alt-002',
    title: 'Palo Alto PCCET Certification Exam Capacity Warning',
    description: 'Slot registration for August 25 exam batch is at 98% capacity (49/50 seats filled).',
    severity: 'HIGH',
    category: 'CoE Operational Capacity',
    timestamp: '4 hours ago',
    affectedEntity: 'Palo Alto Networks CoE',
    actionRequired: true,
  },
  {
    id: 'alt-003',
    title: 'Faculty Over-allocation: Dr. K. Raman (Electronics)',
    description: 'Assigned teaching & lab workload exceeds maximum policy threshold by 4.5 hours/week.',
    severity: 'HIGH',
    category: 'Workload Imbalance',
    timestamp: 'Yesterday at 4:30 PM',
    affectedEntity: 'Electronics Dept',
    actionRequired: true,
  },
  {
    id: 'alt-004',
    title: 'Red Hat EX200 Voucher Renewal Due',
    description: 'Annual institutional discount voucher quota expires in 14 days. 35 unused keys remain.',
    severity: 'MEDIUM',
    category: 'Licensing & Vouchers',
    timestamp: '1 day ago',
    affectedEntity: 'Red Hat Academy CoE',
    actionRequired: false,
  },
  {
    id: 'alt-005',
    title: 'Pending Monthly Operational Audit Report (July)',
    description: 'Civil Engineering Department operational report requires Dean sign-off.',
    severity: 'MEDIUM',
    category: 'Compliance Audit',
    timestamp: '2 days ago',
    affectedEntity: 'Civil Dept',
    actionRequired: false,
  },
  {
    id: 'alt-006',
    title: 'Scheduled Maintenance: CoE Server Rack B',
    description: 'Routine firmware update planned for Saturday 02:00 AM - 05:00 AM.',
    severity: 'LOW',
    category: 'Infrastructure',
    timestamp: '3 days ago',
    affectedEntity: 'Central Computing Lab',
    actionRequired: false,
  },
];
