import { Student } from '@/types/student';

export const MOCK_STUDENTS: Student[] = [
  {
    id: 'STU-2024-001',
    rollNumber: '24CS001',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@student.institution.edu',
    department: 'Computer Science',
    batch: '2024-2028',
    group: 'A1',
    phone: '+91 98765 43210',
    status: 'Active',
    attendancePercentage: 96.4,
    subjectAttendance: [
      { subjectCode: 'CS101', subjectName: 'Data Structures & Algorithms', attended: 44, total: 45, percentage: 97.8 },
      { subjectCode: 'CS102', subjectName: 'Database Management Systems', attended: 38, total: 40, percentage: 95.0 },
      { subjectCode: 'CS103', subjectName: 'Computer Networks', attended: 35, total: 36, percentage: 97.2 },
      { subjectCode: 'MA101', subjectName: 'Discrete Mathematics', attended: 28, total: 30, percentage: 93.3 },
    ],
    trainingTracks: [
      { id: 'tr-1', name: 'Palo Alto Cybersecurity Infrastructure', provider: 'Palo Alto Networks CoE', progress: 100, status: 'Completed', enrolledDate: '2024-01-15' },
      { id: 'tr-2', name: 'Full Stack Web Engineering', provider: 'Internal CoE', progress: 75, status: 'In Progress', enrolledDate: '2024-03-01' },
    ],
    certifications: [
      { id: 'cert-1', name: 'PCCET - Cybersecurity Entry-level Technician', issuingBody: 'Palo Alto Networks', issueDate: '2024-04-10', credentialId: 'PAN-PCCET-98214', status: 'Active' },
    ],
    readiness: {
      overallScore: 92,
      grade: 'A+',
      technicalRating: 94,
      aptitudeRating: 90,
      softSkillsRating: 92,
      recommendation: 'Highly Recommended for Placement & Advanced CoE Lab Fellowship',
    },
    skills: ['Cybersecurity', 'Python', 'React', 'Data Structures', 'PostgreSQL', 'Network Defense'],
    reportAuditStatus: 'Verified',
    lastActive: '10 mins ago',
  },
  {
    id: 'STU-2024-002',
    rollNumber: '24CS012',
    name: 'Ananya Verma',
    email: 'ananya.verma@student.institution.edu',
    department: 'Computer Science',
    batch: '2024-2028',
    group: 'A2',
    phone: '+91 98765 43211',
    status: 'Active',
    attendancePercentage: 91.8,
    subjectAttendance: [
      { subjectCode: 'CS101', subjectName: 'Data Structures & Algorithms', attended: 41, total: 45, percentage: 91.1 },
      { subjectCode: 'CS102', subjectName: 'Database Management Systems', attended: 37, total: 40, percentage: 92.5 },
      { subjectCode: 'CS103', subjectName: 'Computer Networks', attended: 33, total: 36, percentage: 91.6 },
    ],
    trainingTracks: [
      { id: 'tr-3', name: 'Red Hat Certified System Administrator (RHCSA)', provider: 'Red Hat Academy CoE', progress: 60, status: 'In Progress', enrolledDate: '2024-02-10' },
    ],
    certifications: [],
    readiness: {
      overallScore: 86,
      grade: 'A',
      technicalRating: 88,
      aptitudeRating: 85,
      softSkillsRating: 85,
      recommendation: 'Recommended for Core Industry Internship',
    },
    skills: ['Linux Administration', 'Java', 'C++', 'Git', 'Operating Systems'],
    reportAuditStatus: 'Verified',
    lastActive: '1 hour ago',
  },
  {
    id: 'STU-2023-045',
    rollNumber: '23IT045',
    name: 'Rohan Mehta',
    email: 'rohan.mehta@student.institution.edu',
    department: 'Information Tech',
    batch: '2023-2027',
    group: 'B1',
    phone: '+91 98765 43212',
    status: 'Active',
    attendancePercentage: 94.0,
    subjectAttendance: [
      { subjectCode: 'IT201', subjectName: 'Cloud Computing Architecture', attended: 42, total: 44, percentage: 95.4 },
      { subjectCode: 'IT202', subjectName: 'Web Services & Microservices', attended: 36, total: 38, percentage: 94.7 },
    ],
    trainingTracks: [
      { id: 'tr-4', name: 'Red Hat Certified System Administrator (RHCSA)', provider: 'Red Hat Academy CoE', progress: 100, status: 'Completed', enrolledDate: '2023-09-01' },
    ],
    certifications: [
      { id: 'cert-2', name: 'EX200 - Red Hat Certified System Administrator', issuingBody: 'Red Hat Enterprise', issueDate: '2023-12-15', credentialId: 'RH-200-847291', status: 'Active' },
    ],
    readiness: {
      overallScore: 90,
      grade: 'A+',
      technicalRating: 92,
      aptitudeRating: 88,
      softSkillsRating: 90,
      recommendation: 'Target Candidate for Enterprise Cloud Roles',
    },
    skills: ['Ansible', 'RHEL', 'Docker', 'Kubernetes', 'Python', 'DevOps'],
    reportAuditStatus: 'Verified',
    lastActive: '25 mins ago',
  },
  {
    id: 'STU-2023-088',
    rollNumber: '23EC088',
    name: 'Priya Nair',
    email: 'priya.nair@student.institution.edu',
    department: 'Electronics',
    batch: '2023-2027',
    group: 'A1',
    phone: '+91 98765 43213',
    status: 'Active',
    attendancePercentage: 88.5,
    subjectAttendance: [
      { subjectCode: 'EC201', subjectName: 'Microcontrollers & Embedded C', attended: 35, total: 40, percentage: 87.5 },
      { subjectCode: 'EC202', subjectName: 'VLSI Design Fundamentals', attended: 32, total: 36, percentage: 88.8 },
    ],
    trainingTracks: [
      { id: 'tr-5', name: 'IoT Systems & Edge Hardware CoE Track', provider: 'Internal Electronics Lab', progress: 85, status: 'In Progress', enrolledDate: '2023-10-01' },
    ],
    certifications: [],
    readiness: {
      overallScore: 82,
      grade: 'B+',
      technicalRating: 84,
      aptitudeRating: 80,
      softSkillsRating: 82,
      recommendation: 'Eligible for Embedded Systems Training',
    },
    skills: ['Embedded C', 'Arduino', 'Raspberry Pi', 'MATLAB', 'Circuit Design'],
    reportAuditStatus: 'Pending Audit',
    lastActive: '3 hours ago',
  },
  {
    id: 'STU-2022-019',
    rollNumber: '22ME019',
    name: 'Vikram Singh',
    email: 'vikram.singh@student.institution.edu',
    department: 'Mechanical',
    batch: '2022-2026',
    group: 'B1',
    phone: '+91 98765 43214',
    status: 'Active',
    attendancePercentage: 74.2,
    subjectAttendance: [
      { subjectCode: 'ME301', subjectName: 'Thermodynamics & Heat Transfer', attended: 29, total: 40, percentage: 72.5 },
      { subjectCode: 'ME302', subjectName: 'CAD/CAM Simulation', attended: 27, total: 35, percentage: 77.1 },
    ],
    trainingTracks: [
      { id: 'tr-6', name: 'Industrial Automation & Robotics', provider: 'Mechanical CoE Hub', progress: 40, status: 'In Progress', enrolledDate: '2024-01-20' },
    ],
    certifications: [],
    readiness: {
      overallScore: 71,
      grade: 'B',
      technicalRating: 75,
      aptitudeRating: 70,
      softSkillsRating: 68,
      recommendation: 'Requires Remedial Attendance Support & Special Mentorship',
    },
    skills: ['AutoCAD', 'SolidWorks', 'Thermodynamics', 'CNC Programming'],
    reportAuditStatus: 'Requires Review',
    lastActive: 'Yesterday',
  },
  {
    id: 'STU-2024-104',
    rollNumber: '24CE014',
    name: 'Sneha Kulkarni',
    email: 'sneha.kulkarni@student.institution.edu',
    department: 'Civil',
    batch: '2024-2028',
    group: 'A2',
    phone: '+91 98765 43215',
    status: 'Active',
    attendancePercentage: 89.2,
    subjectAttendance: [
      { subjectCode: 'CE101', subjectName: 'Structural Mechanics', attended: 36, total: 40, percentage: 90.0 },
      { subjectCode: 'CE102', subjectName: 'Fluid Dynamics & Hydrology', attended: 31, total: 35, percentage: 88.5 },
    ],
    trainingTracks: [],
    certifications: [],
    readiness: {
      overallScore: 79,
      grade: 'B+',
      technicalRating: 80,
      aptitudeRating: 78,
      softSkillsRating: 79,
      recommendation: 'Recommended for Civil Infra Certification Track',
    },
    skills: ['STAAD Pro', 'Surveying', 'Structural Analysis'],
    reportAuditStatus: 'Verified',
    lastActive: '5 hours ago',
  },
  {
    id: 'STU-2023-112',
    rollNumber: '23CS112',
    name: 'Devraj Iyer',
    email: 'devraj.iyer@student.institution.edu',
    department: 'Computer Science',
    batch: '2023-2027',
    group: 'B2',
    phone: '+91 98765 43216',
    status: 'Active',
    attendancePercentage: 95.1,
    subjectAttendance: [
      { subjectCode: 'CS201', subjectName: 'Advanced Java & Spring Boot', attended: 43, total: 45, percentage: 95.5 },
    ],
    trainingTracks: [
      { id: 'tr-7', name: 'Palo Alto Network Security Professional', provider: 'Palo Alto Networks CoE', progress: 90, status: 'In Progress', enrolledDate: '2023-11-05' },
    ],
    certifications: [
      { id: 'cert-3', name: 'PCCET - Cybersecurity Entry-level Technician', issuingBody: 'Palo Alto Networks', issueDate: '2024-01-20', credentialId: 'PAN-PCCET-10293', status: 'Active' },
    ],
    readiness: {
      overallScore: 93,
      grade: 'A+',
      technicalRating: 96,
      aptitudeRating: 91,
      softSkillsRating: 92,
      recommendation: 'Top Performing CoE Student Scholar',
    },
    skills: ['Cybersecurity', 'Spring Boot', 'Java', 'Docker', 'REST APIs'],
    reportAuditStatus: 'Verified',
    lastActive: '2 mins ago',
  },
  {
    id: 'STU-2024-150',
    rollNumber: '24IT030',
    name: 'Kavya Deshmukh',
    email: 'kavya.deshmukh@student.institution.edu',
    department: 'Information Tech',
    batch: '2024-2028',
    group: 'A1',
    phone: '+91 98765 43217',
    status: 'Active',
    attendancePercentage: 92.0,
    subjectAttendance: [
      { subjectCode: 'IT101', subjectName: 'Object Oriented Programming', attended: 37, total: 40, percentage: 92.5 },
    ],
    trainingTracks: [
      { id: 'tr-8', name: 'Cloud Infrastructure Essentials', provider: 'Internal CoE', progress: 100, status: 'Completed', enrolledDate: '2024-02-01' },
    ],
    certifications: [],
    readiness: {
      overallScore: 84,
      grade: 'A',
      technicalRating: 85,
      aptitudeRating: 83,
      softSkillsRating: 84,
      recommendation: 'Ready for Advanced Red Hat Certification Track',
    },
    skills: ['Python', 'SQL', 'Linux', 'HTML/CSS'],
    reportAuditStatus: 'Verified',
    lastActive: '4 hours ago',
  },
];
