"""add import_type to import_jobs

Revision ID: 3613d151db58
Revises: ba928037d3dc
Create Date: 2026-08-15 01:11:11.922004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3613d151db58'
down_revision: Union[str, Sequence[str], None] = 'ba928037d3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_jobs', sa.Column('import_type', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_jobs', 'import_type')
    # ### end Alembic commands ###
