"""add file_path, file_hash, validation_result to import_jobs

Revision ID: 37bebe8a4e74
Revises: 853b55369e94
Create Date: 2026-08-14 13:49:24.781997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37bebe8a4e74'
down_revision: Union[str, Sequence[str], None] = '853b55369e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_errors_import_id'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index(op.f('ix_imports_file_hash'), table_name='imports')
    op.drop_table('imports')
    op.add_column('import_jobs', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('import_jobs', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('import_jobs', sa.Column('validation_result', sa.Text(), nullable=True))
    op.create_index(op.f('ix_import_jobs_file_hash'), 'import_jobs', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_jobs_file_hash'), table_name='import_jobs')
    op.drop_column('import_jobs', 'validation_result')
    op.drop_column('import_jobs', 'file_hash')
    op.drop_column('import_jobs', 'file_path')
    op.create_table('import_errors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sheet', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('column_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], name=op.f('import_errors_import_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('import_errors_pkey'))
    )
    op.create_index(op.f('ix_import_errors_import_id'), 'import_errors', ['import_id'], unique=False)
    op.create_table('imports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('imports_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('imports_pkey'))
    )
    op.create_index(op.f('ix_imports_file_hash'), 'imports', ['file_hash'], unique=False)
    # ### end Alembic commands ###
