"""add coe and enhance training

Revision ID: 855012450635
Revises: 853b55369e94
Create Date: 2026-08-14 13:28:50.879054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '855012450635'
down_revision: Union[str, Sequence[str], None] = '853b55369e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coe_labs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coe_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coe_id'], ['coes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('training_programs', sa.Column('coe_id', sa.Integer(), nullable=False))
    op.add_column('training_programs', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('training_programs', sa.Column('technology_id', sa.Integer(), nullable=False))
    op.add_column('training_programs', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('training_programs', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('training_programs', sa.Column('planned_hours', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'training_programs', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'training_programs', 'coes', ['coe_id'], ['id'])
    op.create_foreign_key(None, 'training_programs', 'technologies', ['technology_id'], ['id'])
    op.add_column('training_sessions', sa.Column('faculty_id', sa.Integer(), nullable=False))
    op.add_column('training_sessions', sa.Column('start_at', sa.DateTime(), nullable=False))
    op.add_column('training_sessions', sa.Column('end_at', sa.DateTime(), nullable=False))
    op.add_column('training_sessions', sa.Column('hours', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'training_sessions', 'faculty', ['faculty_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_sessions', type_='foreignkey')
    op.drop_column('training_sessions', 'hours')
    op.drop_column('training_sessions', 'end_at')
    op.drop_column('training_sessions', 'start_at')
    op.drop_column('training_sessions', 'faculty_id')
    op.drop_constraint(None, 'training_programs', type_='foreignkey')
    op.drop_constraint(None, 'training_programs', type_='foreignkey')
    op.drop_constraint(None, 'training_programs', type_='foreignkey')
    op.drop_column('training_programs', 'planned_hours')
    op.drop_column('training_programs', 'end_date')
    op.drop_column('training_programs', 'start_date')
    op.drop_column('training_programs', 'technology_id')
    op.drop_column('training_programs', 'company_id')
    op.drop_column('training_programs', 'coe_id')
    op.drop_table('coe_labs')
    op.drop_table('technologies')
    op.drop_table('companies')
    op.drop_table('coes')
    # ### end Alembic commands ###
